version: 2.1

jobs:
  e2e_tests:
    docker:
      - name: dev
        image: circleci/node:16

      - name: postgres-dev
        image: circleci/postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB_NAME: nest
          POSTGRES_PASSWORD: cci

    environment:
      PORT: 3333
      JWT_SECRET: supersecret
      DATABASE_URL: postgresql://postgres:cci@localhost:5432/nest?schema=public

    steps:
      - run:
          name: Update apt-get
          command: sudo apt-get update
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build Project
          command: npm run build
      - run:
          name: Wait for DB to become available
          command: dockerize -wait tcp://postgres-dev:5432 -timeout 30s
      - run:
          name: Run unit tests
          command: npm run test-e2e
      - run:
          name: Stop app
          command: pkill -SIGQUIT node

workflows:
  tests:
    jobs:
      - e2e_tests
